apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: hello-nginx-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx-html
data:
  index.html: |
    <html>
    <head><title>Hello Kubernetes</title></head>
    <body>
      <h1 style="text-align:center; margin-top:50px;">HelloOoooOOO Kubernetes!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
spec:
  selector:
    app: hello-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
